/* This file was generated by the Hex-Rays decompiler version 9.3.0.260213.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

NTSTATUS __stdcall WdmlibRtlInitUnicodeStringEx(PUNICODE_STRING DestinationString, PCWSTR SourceString);
__int64 __fastcall GSHandlerCheckCommon(__int64 a1, __int64 a2);
__int64 __fastcall GSHandlerCheck(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
void *__cdecl memset(void *Dst, int Val, size_t Size);
void *__cdecl memmove(void *Dst, const void *Src, size_t MaxCount);
void __cdecl __noreturn report_gsfailure(uintptr_t StackCookie);
void __fastcall DbgPrint_Stub(const char *);
__int64 SafeStringCchVPrintfW(wchar_t *Dest, __int64, const wchar_t *, ...);
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath);
__int64 __fastcall DispatchCreateClose(__int64, IRP *);
__int64 __fastcall DispatchClose(__int64, IRP *);
__int64 __fastcall IrpSuccess_Stub(__int64, IRP *);
void __fastcall DriverUnload(__int64);
__int64 __fastcall NotImplemented_Stub(__int64, IRP *);
__int64 __fastcall DispatchTable(__int64, __int64);
// int snwprintf(wchar_t *Dest, size_t Count, const wchar_t *Format, ...);
// wchar_t *__cdecl wcschr(const wchar_t *Str, wchar_t Ch);
// int __cdecl wcsnicmp(const wchar_t *Str1, const wchar_t *Str2, size_t MaxCount);
// __int64 __fastcall SeCaptureSecurityDescriptor(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
PVOID WdmlibInit();
NTSTATUS __stdcall WdmlibIoCreateDeviceSecure(PDRIVER_OBJECT DriverObject, ULONG DeviceExtensionSize, PUNICODE_STRING DeviceName, ULONG DeviceType, ULONG DeviceCharacteristics, BOOLEAN Exclusive, PCUNICODE_STRING DefaultSDDLString, LPCGUID DeviceClassGuid, PDEVICE_OBJECT *DeviceObject);
__int64 __fastcall IopDevObjApplyPostCreationSettings(PVOID Object);
// __int64 __usercall IoDevObjCreateDeviceSecure@<rax>(PDRIVER_OBJECT DriverObject@<rcx>, ULONG DeviceExtensionSize@<edx>, PUNICODE_STRING DeviceName@<r8>, int, char, __int64, __int64, PDEVICE_OBJECT);
void __fastcall PpRegStateLoadSecurityDescriptor(__int64 a1, __int64 a2);
void __fastcall PpRegStateFreeStackCreationSettings(__int64 a1);
int __fastcall PiRegStateOpenClassKey(unsigned int *a1, ACCESS_MASK a2, int a3, int *a4, _QWORD *a5);
__int64 __fastcall PpRegStateInitEmptyCreationSettings(__int64 a1);
__int64 __fastcall PiRegStateReadStackCreationSettingsFromKey(void *a1, __int64 a2);
int __fastcall PpRegStateReadCreateClassCreationSettings(unsigned int *a1, __int64 a2, __int64 a3);
int __fastcall PpRegStateUpdateStackCreationSettings(unsigned int *a1, __int64 a2);
__int64 __fastcall SepSddlParseWideStringUlong(unsigned __int16 *a1, unsigned __int16 **a2, unsigned int *a3);
__int64 __fastcall SepSddlAddAceToAcl(int, int, int, int, ACCESS_MASK AccessMask, int, PSID Sid);
__int64 __fastcall SepSddlLookupAccessMaskInTable(wchar_t *Str1);
__int64 __fastcall SepSddlGetSidForString(wchar_t *Str1);
__int64 __fastcall SepSddlGetAclForString(wchar_t *Str1, int);
__int64 __fastcall SepSddlDaclFromSDDLString(_WORD *a1, int a2, int *a3, PVOID *a4);
__int64 __fastcall SepSddlSecurityDescriptorFromSDDLString(__int64, __int64, _QWORD *);
__int64 __fastcall SeSddlSecurityDescriptorFromSDDL(unsigned __int16 *a1, unsigned int a2, _QWORD *a3);
void __fastcall SeSetSecurityAccessMask(char a1, _DWORD *a2);
__int64 __fastcall SeUtilSecurityInfoFromSecurityDescriptor(PSECURITY_DESCRIPTOR SecurityDescriptor);
__int64 __fastcall CmpRegUtilAllocateUnicodeString(__int64 a1, unsigned __int16 a2);
__int64 __fastcall CmRegUtilUcValueSetUcString(HANDLE KeyHandle, PUNICODE_STRING ValueName);
NTSTATUS __fastcall CmRegUtilUcValueGetDword(void *a1, struct _UNICODE_STRING *a2, int a3, _DWORD *a4);
__int64 __fastcall CmRegUtilCreateUcKey(void *a1, struct _UNICODE_STRING *a2, ACCESS_MASK a3, ULONG a4, void *a5, _DWORD *a6, _QWORD *a7);
NTSTATUS __fastcall CmRegUtilOpenExistingUcKey(void *a1, struct _UNICODE_STRING *a2, ACCESS_MASK a3, _QWORD *a4);
__int64 __fastcall CmRegUtilWstrValueSetWstrString(HANDLE KeyHandle, PCWSTR SourceString, PCWSTR);
__int64 __fastcall CmRegUtilWstrValueSetUcString(HANDLE KeyHandle);
// __int64 __usercall CmRegUtilWstrValueSetFullBuffer@<rax>(HANDLE KeyHandle@<rcx>, ULONG);
int __fastcall CmRegUtilWstrValueGetDword(void *a1, const WCHAR *a2, int a3, _DWORD *a4);
NTSTATUS __fastcall CmRegUtilCreateWstrKey(void *a1, const WCHAR *a2, ACCESS_MASK a3, ULONG a4, void *a5, _DWORD *a6, _QWORD *a7);
int __fastcall CmRegUtilOpenExistingWstrKey(void *a1, const WCHAR *a2, ACCESS_MASK a3, _QWORD *a4);
// __int64 __usercall CmRegUtilUcValueGetFullBuffer@<rax>(HANDLE KeyHandle@<rcx>, PUNICODE_STRING ValueName@<rdx>, __int64);
// __int64 __usercall CmRegUtilWstrValueGetFullBuffer@<rax>(HANDLE KeyHandle@<rcx>, __int64);

//-------------------------------------------------------------------------
// Data declarations

// extern void (__stdcall *RtlInitUnicodeString)(PUNICODE_STRING DestinationString, PCWSTR SourceString);
// extern void (__stdcall *IoDeleteDevice)(PDEVICE_OBJECT DeviceObject);
// extern void (__stdcall *RtlCopyUnicodeString)(PUNICODE_STRING DestinationString, PCUNICODE_STRING SourceString);
// extern NTSTATUS (__stdcall *IoRegisterShutdownNotification)(PDEVICE_OBJECT DeviceObject);
// extern PVOID (__stdcall *ExAllocatePoolWithTag)(POOL_TYPE PoolType, SIZE_T NumberOfBytes, ULONG Tag);
// extern void (__stdcall *ExFreePoolWithTag)(PVOID P, ULONG Tag);
// extern NTSTATUS (__stdcall *IoCreateSymbolicLink)(PUNICODE_STRING SymbolicLinkName, PUNICODE_STRING DeviceName);
// extern wchar_t *(__cdecl *wcsrchr)(const wchar_t *Str, wchar_t Ch);
// extern PVOID (__stdcall *MmGetSystemRoutineAddress)(PUNICODE_STRING SystemRoutineName);
// extern void (__stdcall *RtlFreeUnicodeString)(PUNICODE_STRING UnicodeString);
// extern NTSTATUS (__stdcall *IoCreateDevice)(PDRIVER_OBJECT DriverObject, ULONG DeviceExtensionSize, PUNICODE_STRING DeviceName, ULONG DeviceType, ULONG DeviceCharacteristics, BOOLEAN Exclusive, PDEVICE_OBJECT *DeviceObject);
// extern NTSTATUS (__stdcall *ZwClose)(HANDLE Handle);
// extern NTSTATUS (__stdcall *ObOpenObjectByPointer)(PVOID Object, ULONG HandleAttributes, PACCESS_STATE PassedAccessState, ACCESS_MASK DesiredAccess, POBJECT_TYPE ObjectType, KPROCESSOR_MODE AccessMode, PHANDLE Handle);
// extern NTSTATUS (__stdcall *ZwSetSecurityObject)(HANDLE Handle, SECURITY_INFORMATION SecurityInformation, PSECURITY_DESCRIPTOR SecurityDescriptor);
// extern _UNKNOWN IoDeviceObjectType; weak
// extern ULONG (__stdcall *RtlLengthSecurityDescriptor)(PSECURITY_DESCRIPTOR SecurityDescriptor);
// extern BOOLEAN (__stdcall *IoIsWdmVersionAvailable)(UCHAR MajorVersion, UCHAR MinorVersion);
// extern PSE_EXPORTS SeExports;
// extern ULONG (__stdcall *RtlLengthSid)(PSID Sid);
// extern NTSTATUS (__stdcall *RtlAddAccessAllowedAce)(PACL Acl, ULONG AceRevision, ACCESS_MASK AccessMask, PSID Sid);
// extern NTSTATUS (__stdcall *RtlGetSaclSecurityDescriptor)(PSECURITY_DESCRIPTOR SecurityDescriptor, PBOOLEAN SaclPresent, PACL *Sacl, PBOOLEAN SaclDefaulted);
// extern NTSTATUS (__stdcall *RtlGetDaclSecurityDescriptor)(PSECURITY_DESCRIPTOR SecurityDescriptor, PBOOLEAN DaclPresent, PACL *Dacl, PBOOLEAN DaclDefaulted);
// extern NTSTATUS (__stdcall *RtlGetGroupSecurityDescriptor)(PSECURITY_DESCRIPTOR SecurityDescriptor, PSID *Group, PBOOLEAN GroupDefaulted);
// extern NTSTATUS (__stdcall *RtlGetOwnerSecurityDescriptor)(PSECURITY_DESCRIPTOR SecurityDescriptor, PSID *Owner, PBOOLEAN OwnerDefaulted);
// extern NTSTATUS (__stdcall *ZwOpenKey)(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes);
// extern NTSTATUS (__stdcall *ZwCreateKey)(PHANDLE KeyHandle, ACCESS_MASK DesiredAccess, POBJECT_ATTRIBUTES ObjectAttributes, ULONG TitleIndex, PUNICODE_STRING Class, ULONG CreateOptions, PULONG Disposition);
// extern NTSTATUS (__stdcall *ZwQueryValueKey)(HANDLE KeyHandle, PUNICODE_STRING ValueName, KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass, PVOID KeyValueInformation, ULONG Length, PULONG ResultLength);
// extern NTSTATUS (__stdcall *ZwSetValueKey)(HANDLE KeyHandle, PUNICODE_STRING ValueName, ULONG TitleIndex, ULONG Type, PVOID Data, ULONG DataSize);
// extern void (__stdcall __noreturn *KeBugCheckEx)(ULONG BugCheckCode, ULONG_PTR BugCheckParameter1, ULONG_PTR BugCheckParameter2, ULONG_PTR BugCheckParameter3, ULONG_PTR BugCheckParameter4);
const UNICODE_STRING DefaultSDDLString = { 54u, 56u, L"D:P(A;;GA;;;SY)(A;;GA;;;BA)" }; // idb
_UNKNOWN unk_140004000; // weak
_UNKNOWN unk_140004030; // weak
_UNKNOWN unk_140004044; // weak
wchar_t *off_140004150 = L"RC"; // weak
ULONG_PTR BugCheckParameter2 = 47936899621426uLL; // idb
ULONG_PTR BugCheckParameter3 = 18446696136809930189uLL; // idb
char byte_1400041E0 = '\0'; // weak
NTSTATUS (__fastcall *qword_1400041E8)(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _DWORD, _QWORD, _QWORD, _QWORD) = NULL; // weak
__int64 qword_1400041F0 = 0LL; // weak
int dword_1400041F8 = 0; // weak
struct _UNICODE_STRING DestinationString; // idb
struct _UNICODE_STRING DriverName; // idb


//----- (0000000140001000) ----------------------------------------------------
NTSTATUS __stdcall WdmlibRtlInitUnicodeStringEx(PUNICODE_STRING DestinationString, PCWSTR SourceString)
{
  __int64 v3; // rcx
  PCWSTR v4; // rdi
  bool v5; // zf
  unsigned __int64 v6; // rcx

  if ( SourceString )
  {
    v3 = -1;
    v4 = SourceString;
    do
    {
      if ( !v3 )
        break;
      v5 = *v4++ == 0;
      --v3;
    }
    while ( !v5 );
    v6 = -v3 - 2;
    if ( v6 > 0x7FFE )
      return -1073741562;
    DestinationString->Buffer = (PWSTR)SourceString;
    DestinationString->Length = 2 * v6;
    DestinationString->MaximumLength = 2 * v6 + 2;
  }
  else
  {
    DestinationString->Length = 0;
    DestinationString->MaximumLength = 0;
    DestinationString->Buffer = nullptr;
  }
  return 0;
}

//----- (000000014000105C) ----------------------------------------------------
__int64 __fastcall GSHandlerCheckCommon(__int64 a1, __int64 a2)
{
  __int64 result; // rax
  __int64 v3; // rcx

  result = *(_QWORD *)(a2 + 16);
  v3 = *(_QWORD *)(a2 + 8) + *(unsigned int *)(result + 8);
  if ( (*(_BYTE *)(v3 + 3) & 0xF) != 0 )
    return *(_BYTE *)(v3 + 3) & 0xF0;
  return result;
}

//----- (00000001400010C0) ----------------------------------------------------
__int64 __fastcall GSHandlerCheck(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  GSHandlerCheckCommon(a2, a4);
  return 1;
}

//----- (00000001400010F0) ----------------------------------------------------
// local variable allocation has failed, the output may be wrong!
void *__cdecl memset(void *Dst, int Val, size_t Size)
{
  void *result; // rax
  unsigned int v4; // ecx
  size_t v5; // r9
  unsigned __int64 v6; // r9
  size_t v7; // r9
  size_t i; // r9
  _UNKNOWN *retaddr; // [rsp+0h] [rbp+0h] BYREF

  result = Dst;
  if ( Size >= 8 )
  {
    *(_QWORD *)&Val = 0x101010101010101LL * (unsigned __int8)Val;
    if ( Size >= 0x40 )
    {
      v4 = -(int)Dst & 7;
      if ( v4 )
      {
        Size -= v4;
        *(_QWORD *)result = *(_QWORD *)&Val;
      }
      Dst = (char *)result + v4;
      v5 = Size;
      Size &= 0x3Fu;
      v6 = v5 >> 6;
      if ( v6 )
      {
        if ( v6 >= 0x1C00 )
        {
          do
          {
            _mm_stream_si32((int *)Dst, Val);
            _mm_stream_si32((int *)Dst + 2, Val);
            _mm_stream_si32((int *)Dst + 4, Val);
            Dst = (char *)Dst + 64;
            _mm_stream_si32((int *)Dst - 10, Val);
            _mm_stream_si32((int *)Dst - 8, Val);
            --v6;
            _mm_stream_si32((int *)Dst - 6, Val);
            _mm_stream_si32((int *)Dst - 4, Val);
            _mm_stream_si32((int *)Dst - 2, Val);
          }
          while ( v6 );
          _InterlockedOr8((volatile signed __int8 *)&retaddr, 0);
        }
        else
        {
          do
          {
            *(_QWORD *)Dst = *(_QWORD *)&Val;
            *((_QWORD *)Dst + 1) = *(_QWORD *)&Val;
            *((_QWORD *)Dst + 2) = *(_QWORD *)&Val;
            Dst = (char *)Dst + 64;
            *((_QWORD *)Dst - 5) = *(_QWORD *)&Val;
            *((_QWORD *)Dst - 4) = *(_QWORD *)&Val;
            --v6;
            *((_QWORD *)Dst - 3) = *(_QWORD *)&Val;
            *((_QWORD *)Dst - 2) = *(_QWORD *)&Val;
            *((_QWORD *)Dst - 1) = *(_QWORD *)&Val;
          }
          while ( v6 );
        }
      }
    }
    v7 = Size;
    Size &= 7u;
    for ( i = v7 >> 3; i; --i )
    {
      *(_QWORD *)Dst = *(_QWORD *)&Val;
      Dst = (char *)Dst + 8;
    }
  }
  for ( ; Size; --Size )
  {
    *(_BYTE *)Dst = Val;
    Dst = (char *)Dst + 1;
  }
  return result;
}
// 1400010F0: variables would overlap: edx.4 and rdx.8

//----- (00000001400011F0) ----------------------------------------------------
void *__cdecl memmove(void *Dst, const void *Src, size_t MaxCount)
{
  void *v3; // r11
  bool v4; // cf
  unsigned __int64 v5; // rdx
  size_t v6; // r9
  size_t v7; // r9
  __int64 v9; // rax
  __int64 v10; // r10
  __int64 v11; // r10
  int v12; // eax
  int v13; // eax
  __int64 v14; // r10
  __int64 v15; // r10
  __int64 v16; // r9
  __int64 v17; // r10
  __int64 v18; // r10
  int *v19; // rcx
  size_t v20; // r9
  size_t v21; // r9
  __int64 v22; // rax
  __int64 v23; // r10
  __int64 v24; // r10
  int v25; // eax
  int v26; // eax
  __int64 v27; // r10
  __int64 v28; // r10
  __int64 v29; // r9
  __int64 v30; // r10
  __int64 v31; // r10
  _UNKNOWN *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v3 = Dst;
  v4 = Src < Dst;
  v5 = (_BYTE *)Src - (_BYTE *)Dst;
  if ( v4 )
  {
    v19 = (int *)((char *)Dst + MaxCount);
    if ( MaxCount >= 8 )
    {
      if ( ((unsigned __int8)v19 & 7) != 0 )
      {
        if ( ((unsigned __int8)v19 & 1) != 0 )
        {
          v19 = (int *)((char *)v19 - 1);
          --MaxCount;
          *(_BYTE *)v19 = *((_BYTE *)v19 + v5);
        }
        if ( ((unsigned __int8)v19 & 2) != 0 )
        {
          v19 = (int *)((char *)v19 - 2);
          MaxCount -= 2LL;
          *(_WORD *)v19 = *(_WORD *)((char *)v19 + v5);
        }
        if ( ((unsigned __int8)v19 & 4) != 0 )
        {
          --v19;
          MaxCount -= 4LL;
          *v19 = *(int *)((char *)v19 + v5);
        }
      }
      while ( 1 )
      {
        v20 = MaxCount >> 5;
        if ( !(MaxCount >> 5) )
          break;
        if ( v20 < 0x2000 || v5 > 0xFFFFFFFFFFFFF000uLL )
        {
          do
          {
            v22 = *(_QWORD *)((char *)v19 + v5 - 8);
            v23 = *(_QWORD *)((char *)v19 + v5 - 16);
            v19 -= 8;
            *((_QWORD *)v19 + 3) = v22;
            *((_QWORD *)v19 + 2) = v23;
            v24 = *(_QWORD *)((char *)v19 + v5);
            --v20;
            *((_QWORD *)v19 + 1) = *(_QWORD *)((char *)v19 + v5 + 8);
            *(_QWORD *)v19 = v24;
          }
          while ( v20 );
          MaxCount &= 0x1Fu;
          break;
        }
        do
        {
          v25 = 32;
          do
          {
            v19 -= 32;
            _mm_prefetch((const char *)v19 + v5, 0);
            _mm_prefetch((const char *)v19 + v5 + 64, 0);
            --v25;
          }
          while ( v25 );
          v19 += 1024;
          v26 = 64;
          do
          {
            v27 = *(_QWORD *)((char *)v19 + v5 - 16);
            _mm_stream_si32(v19 - 2, *(_QWORD *)((char *)v19 + v5 - 8));
            _mm_stream_si32(v19 - 4, v27);
            v28 = *(_QWORD *)((char *)v19 + v5 - 32);
            _mm_stream_si32(v19 - 6, *(_QWORD *)((char *)v19 + v5 - 24));
            _mm_stream_si32(v19 - 8, v28);
            v29 = *(_QWORD *)((char *)v19 + v5 - 40);
            v30 = *(_QWORD *)((char *)v19 + v5 - 48);
            v19 -= 16;
            _mm_stream_si32(v19 + 6, v29);
            _mm_stream_si32(v19 + 4, v30);
            v31 = *(_QWORD *)((char *)v19 + v5);
            --v26;
            _mm_stream_si32(v19 + 2, *(_QWORD *)((char *)v19 + v5 + 8));
            _mm_stream_si32(v19, v31);
          }
          while ( v26 );
          MaxCount -= 4096LL;
        }
        while ( MaxCount >= 0x1000 );
        _InterlockedOr8((volatile signed __int8 *)&retaddr, 0);
      }
      v21 = MaxCount >> 3;
      if ( MaxCount >> 3 )
      {
        do
        {
          v19 -= 2;
          --v21;
          *(_QWORD *)v19 = *(_QWORD *)((char *)v19 + v5);
        }
        while ( v21 );
        MaxCount &= 7u;
      }
    }
    if ( MaxCount )
    {
      do
      {
        v19 = (int *)((char *)v19 - 1);
        --MaxCount;
        *(_BYTE *)v19 = *((_BYTE *)v19 + v5);
      }
      while ( MaxCount );
      return v3;
    }
    else
    {
      return v3;
    }
  }
  else
  {
    if ( MaxCount >= 8 )
    {
      if ( ((unsigned __int8)Dst & 7) != 0 )
      {
        if ( ((unsigned __int8)Dst & 1) != 0 )
        {
          --MaxCount;
          *(_BYTE *)Dst = *((_BYTE *)Dst + v5);
          Dst = (char *)Dst + 1;
        }
        if ( ((unsigned __int8)Dst & 2) != 0 )
        {
          MaxCount -= 2LL;
          *(_WORD *)Dst = *(_WORD *)((char *)Dst + v5);
          Dst = (char *)Dst + 2;
        }
        if ( ((unsigned __int8)Dst & 4) != 0 )
        {
          MaxCount -= 4LL;
          *(_DWORD *)Dst = *(_DWORD *)((char *)Dst + v5);
          Dst = (char *)Dst + 4;
        }
      }
      while ( 1 )
      {
        v6 = MaxCount >> 5;
        if ( !(MaxCount >> 5) )
          break;
        if ( v6 < 0x2000 || v5 < 0x1000 )
        {
          do
          {
            v9 = *(_QWORD *)((char *)Dst + v5);
            v10 = *(_QWORD *)((char *)Dst + v5 + 8);
            Dst = (char *)Dst + 32;
            *((_QWORD *)Dst - 4) = v9;
            *((_QWORD *)Dst - 3) = v10;
            v11 = *(_QWORD *)((char *)Dst + v5 - 8);
            --v6;
            *((_QWORD *)Dst - 2) = *(_QWORD *)((char *)Dst + v5 - 16);
            *((_QWORD *)Dst - 1) = v11;
          }
          while ( v6 );
          MaxCount &= 0x1Fu;
          break;
        }
        do
        {
          v12 = 32;
          do
          {
            _mm_prefetch((const char *)Dst + v5, 0);
            _mm_prefetch((const char *)Dst + v5 + 64, 0);
            Dst = (char *)Dst + 128;
            --v12;
          }
          while ( v12 );
          Dst = (char *)Dst - 4096;
          v13 = 64;
          do
          {
            v14 = *(_QWORD *)((char *)Dst + v5 + 8);
            _mm_stream_si32((int *)Dst, *(_QWORD *)((char *)Dst + v5));
            _mm_stream_si32((int *)Dst + 2, v14);
            v15 = *(_QWORD *)((char *)Dst + v5 + 24);
            _mm_stream_si32((int *)Dst + 4, *(_QWORD *)((char *)Dst + v5 + 16));
            _mm_stream_si32((int *)Dst + 6, v15);
            v16 = *(_QWORD *)((char *)Dst + v5 + 32);
            v17 = *(_QWORD *)((char *)Dst + v5 + 40);
            Dst = (char *)Dst + 64;
            _mm_stream_si32((int *)Dst - 8, v16);
            _mm_stream_si32((int *)Dst - 6, v17);
            v18 = *(_QWORD *)((char *)Dst + v5 - 8);
            --v13;
            _mm_stream_si32((int *)Dst - 4, *(_QWORD *)((char *)Dst + v5 - 16));
            _mm_stream_si32((int *)Dst - 2, v18);
          }
          while ( v13 );
          MaxCount -= 4096LL;
        }
        while ( MaxCount >= 0x1000 );
        _InterlockedOr8((volatile signed __int8 *)&retaddr, 0);
      }
      v7 = MaxCount >> 3;
      if ( MaxCount >> 3 )
      {
        do
        {
          *(_QWORD *)Dst = *(_QWORD *)((char *)Dst + v5);
          Dst = (char *)Dst + 8;
          --v7;
        }
        while ( v7 );
        MaxCount &= 7u;
      }
    }
    if ( MaxCount )
    {
      do
      {
        *(_BYTE *)Dst = *((_BYTE *)Dst + v5);
        Dst = (char *)Dst + 1;
        --MaxCount;
      }
      while ( MaxCount );
      return v3;
    }
    else
    {
      return v3;
    }
  }
}

//----- (0000000140001560) ----------------------------------------------------
void __cdecl __noreturn report_gsfailure(uintptr_t StackCookie)
{
  KeBugCheckEx(0xF7u, StackCookie, BugCheckParameter2, BugCheckParameter3, 0);
}

//----- (0000000140001590) ----------------------------------------------------
void __fastcall DbgPrint_Stub(const char *a1)
{
  ;
}

//----- (00000001400015A0) ----------------------------------------------------
__int64 SafeStringCchVPrintfW(wchar_t *Dest, __int64 a2, const wchar_t *a3, ...)
{
  unsigned int v3; // ebx
  int v5; // r9d
  unsigned __int64 v6; // rdi
  int v7; // eax
  __int64 result; // rax
  va_list Args; // [rsp+58h] [rbp+20h] BYREF

  va_start(Args, a3);
  v3 = 0;
  v5 = 0;
  if ( (unsigned __int64)(a2 - 1) > 0x7FFFFFFE )
    v5 = -1073741811;
  if ( v5 < 0 )
  {
    result = (unsigned int)v5;
    if ( a2 )
      *Dest = 0;
  }
  else
  {
    v6 = a2 - 1;
    v7 = vsnwprintf(Dest, a2 - 1, a3, Args);
    if ( v7 < 0 || v7 > v6 )
    {
      Dest[v6] = 0;
      return (unsigned int)-2147483643;
    }
    else if ( v7 == v6 )
    {
      Dest[v6] = 0;
      return 0;
    }
    return v3;
  }
  return result;
}

//----- (0000000140001640) ----------------------------------------------------
NTSTATUS __stdcall DriverEntry(PDRIVER_OBJECT DriverObject, PUNICODE_STRING RegistryPath)
{
  wchar_t *WinRegPath; // rax
  int NTSTATUS; // ebx
  _QWORD *DeviceExtension; // rbx
  struct _UNICODE_STRING DeviceName; // [rsp+50h] [rbp-438h] BYREF
  struct _UNICODE_STRING DestinationString; // [rsp+60h] [rbp-428h] BYREF
  struct _UNICODE_STRING SymbolicLinkName; // [rsp+70h] [rbp-418h] BYREF
  WCHAR SourceString[256]; // [rsp+80h] [rbp-408h] BYREF
  WCHAR Dest[260]; // [rsp+280h] [rbp-208h] BYREF
  PDEVICE_OBJECT DeviceObject; // [rsp+498h] [rbp+10h] BYREF

  *(_QWORD *)&::DestinationString.Length = 0;
  ::DestinationString.Buffer = nullptr;
  *(_QWORD *)&DriverName.Length = 0;
  DriverName.Buffer = nullptr;
  WinRegPath = wcsrchr(RegistryPath->Buffer, 0x5Cu);
  RtlInitUnicodeString(&DestinationString, WinRegPath + 1);
  ::DestinationString.Length = DestinationString.Length;
  ::DestinationString.MaximumLength = DestinationString.Length + 2;
  ::DestinationString.Buffer = (PWSTR)ExAllocatePoolWithTag(
                                        PagedPool,
                                        (unsigned __int16)(DestinationString.Length + 2),
                                        0x76697244u);
  if ( !::DestinationString.Buffer )
    return -1073741670;
  RtlCopyUnicodeString(&::DestinationString, &DestinationString);
  DriverName.Length = RegistryPath->Length;
  DriverName.MaximumLength = RegistryPath->Length + 2;
  DriverName.Buffer = (PWSTR)ExAllocatePoolWithTag(PagedPool, DriverName.MaximumLength, 0x76697244u);
  if ( !DriverName.Buffer )
    return -1073741670;
  RtlCopyUnicodeString(&DriverName, RegistryPath);
  DriverObject->MajorFunction[0] = (PDRIVER_DISPATCH)DispatchCreateClose;
  DriverObject->MajorFunction[2] = (PDRIVER_DISPATCH)DispatchClose;
  DriverObject->MajorFunction[14] = (PDRIVER_DISPATCH)DispatchTable;
  DriverObject->MajorFunction[18] = (PDRIVER_DISPATCH)IrpSuccess_Stub;
  DriverObject->MajorFunction[16] = (PDRIVER_DISPATCH)NotImplemented_Stub;
  DriverObject->DriverUnload = (PDRIVER_UNLOAD)DriverUnload;
  SafeStringCchVPrintfW(SourceString, 255, L"\\Device\\%ls", ::DestinationString.Buffer);
  RtlInitUnicodeString(&DeviceName, SourceString);
  NTSTATUS = WdmlibIoCreateDeviceSecure(
               DriverObject,
               0x2818u,
               &DeviceName,
               0x22u,
               0x100u,
               0,
               &DefaultSDDLString,
               nullptr,
               &DeviceObject);
  if ( NTSTATUS < 0 )
  {
LABEL_6:
    ExFreePoolWithTag(DriverName.Buffer, 0);
    DriverName.Buffer = nullptr;
    return NTSTATUS;
  }
  DbgPrint_Stub("Created device: %S");
  DeviceExtension = DeviceObject->DeviceExtension;
  memset(DeviceExtension, 0, 0x2818u);
  *DeviceExtension = DeviceObject;
  DeviceObject->Flags |= 0x10u;
  SafeStringCchVPrintfW(Dest, 255, L"\\??\\%ls", ::DestinationString.Buffer);
  RtlInitUnicodeString(&SymbolicLinkName, Dest);
  NTSTATUS = IoCreateSymbolicLink(&SymbolicLinkName, &DeviceName);
  if ( NTSTATUS < 0 )
  {
    IoDeleteDevice(DeviceObject);
    goto LABEL_6;
  }
  DbgPrint_Stub("Created link: %S -> %S");
  IoRegisterShutdownNotification(DeviceObject);
  DeviceObject->Flags &= ~0x80u;
  return NTSTATUS;
}
// 140003720: using guessed type wchar_t aDeviceLs[12];
// 140003750: using guessed type wchar_t aLs[8];

//----- (0000000140001920) ----------------------------------------------------
__int64 __fastcall DispatchCreateClose(__int64 a1, IRP *a2)
{
  _InterlockedIncrement((volatile signed __int32 *)(*(_QWORD *)(a1 + 64) + 8LL));
  a2->IoStatus.Information = 0;
  a2->IoStatus.Status = 0;
  IofCompleteRequest(a2, 0);
  return 0;
}

//----- (0000000140001950) ----------------------------------------------------
__int64 __fastcall DispatchClose(__int64 a1, IRP *a2)
{
  __int64 v2; // rbx

  v2 = *(_QWORD *)(a1 + 64);
  a2->IoStatus.Information = 0;
  a2->IoStatus.Status = 0;
  IofCompleteRequest(a2, 0);
  _InterlockedDecrement((volatile signed __int32 *)(v2 + 8));
  return 0;
}

//----- (0000000140001980) ----------------------------------------------------
__int64 __fastcall IrpSuccess_Stub(__int64 a1, IRP *a2)
{
  a2->IoStatus.Information = 0;
  a2->IoStatus.Status = 0;
  IofCompleteRequest(a2, 0);
  return 0;
}

//----- (00000001400019B0) ----------------------------------------------------
void __fastcall DriverUnload(__int64 a1)
{
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-218h] BYREF
  WCHAR SourceString[260]; // [rsp+30h] [rbp-208h] BYREF

  SafeStringCchVPrintfW(SourceString, 255, L"\\??\\%ls", ::DestinationString.Buffer);
  RtlInitUnicodeString(&DestinationString, SourceString);
  IoDeleteSymbolicLink(&DestinationString);
  DbgPrint_Stub("Deleted link: %S");
  IoUnregisterShutdownNotification(*(PDEVICE_OBJECT *)(a1 + 8));
  IoDeleteDevice(*(PDEVICE_OBJECT *)(a1 + 8));
  if ( DriverName.Buffer )
  {
    ExFreePoolWithTag(DriverName.Buffer, 0);
    DriverName.Buffer = nullptr;
  }
  if ( ::DestinationString.Buffer )
  {
    ExFreePoolWithTag(::DestinationString.Buffer, 0);
    ::DestinationString.Buffer = nullptr;
  }
}
// 140003750: using guessed type wchar_t aLs[8];

//----- (0000000140001A60) ----------------------------------------------------
__int64 __fastcall NotImplemented_Stub(__int64 a1, IRP *a2)
{
  a2->IoStatus.Status = -1073741822;
  a2->IoStatus.Information = 0;
  IofCompleteRequest(a2, 0);
  return 3221225474LL;
}

//----- (0000000140001A90) ----------------------------------------------------
__int64 __fastcall IoctlWriteMsr(__int64 a1, __int64 a2)
{
  __int64 v3; // rdx
  unsigned int v4; // ecx

  if ( *(_DWORD *)(a1 + 8) )
  {
    *(_QWORD *)(a2 + 56) = 0;
    return 3221225990LL;
  }
  else if ( *(_DWORD *)(a1 + 16) == 12 )
  {
    v3 = *(_QWORD *)(a2 + 24);
    v4 = *(_DWORD *)v3;
    if ( (unsigned int)(*(_DWORD *)v3 + 1073741695) <= 2 || v4 - 372 <= 2 )
    {
      return 3221225485LL;
    }
    else
    {
      __writemsr(v4, *(_QWORD *)(v3 + 4));
      return 0;
    }
  }
  else
  {
    *(_QWORD *)(a2 + 56) = 12;
    return 3221225990LL;
  }
}

//----- (0000000140001B00) ----------------------------------------------------
__int64 __fastcall IoctlReadMsr(__int64 a1, __int64 a2)
{
  if ( *(_DWORD *)(a1 + 8) == 8 )
  {
    if ( *(_DWORD *)(a1 + 16) == 4 )
    {
      **(_QWORD **)(a2 + 24) = __readmsr(**(_DWORD **)(a2 + 24));
      return 0;
    }
    else
    {
      *(_QWORD *)(a2 + 56) = 4;
      return 3221225990LL;
    }
  }
  else
  {
    *(_QWORD *)(a2 + 56) = 8;
    return 3221225990LL;
  }
}

//----- (0000000140001B50) ----------------------------------------------------
__int64 __fastcall IoctlMapPhysicalMemory(__int64 a1, __int64 a2, __int64 a3)
{
  PHYSICAL_ADDRESS *v5; // r15
  PVOID v6; // rax
  PVOID v7; // r13
  int v9; // edi
  struct _MDL *Mdl; // rax
  struct _MDL *v11; // r12
  PVOID v12; // r14
  int v13; // eax
  __int64 v14; // rcx
  _DWORD *v15; // rax
  __int64 v16; // rbx

  if ( ((*(_DWORD *)(a2 + 8) - 4) & 0xFFFFFFFB) != 0 )
  {
    *(_QWORD *)(a3 + 56) = 4;
    return 3221225990LL;
  }
  if ( *(_DWORD *)(a2 + 16) != 12 )
  {
    *(_QWORD *)(a3 + 56) = 12;
    return 3221225990LL;
  }
  v5 = *(PHYSICAL_ADDRESS **)(a3 + 24);
  v6 = MmMapIoSpace(*v5, v5[1].LowPart, MmNonCached);
  v7 = v6;
  if ( !v6 )
    return 3221225473LL;
  v9 = 0;
  Mdl = IoAllocateMdl(v6, v5[1].LowPart, 0, 0, nullptr);
  v11 = Mdl;
  if ( !Mdl )
    return 3221225473LL;
  MmBuildMdlForNonPagedPool(Mdl);
  v12 = MmMapLockedPagesSpecifyCache(v11, 1, MmNonCached, nullptr, 0, 0x10u);
  v13 = *(_DWORD *)(a2 + 8);
  if ( v13 == 4 )
  {
    **(_DWORD **)(a3 + 24) = (_DWORD)v12;
    v13 = *(_DWORD *)(a2 + 8);
  }
  if ( v13 == 8 )
    **(_QWORD **)(a3 + 24) = v12;
  v14 = 0;
  v15 = (_DWORD *)(a1 + 48);
  while ( *v15 )
  {
    ++v9;
    ++v14;
    v15 += 10;
    if ( v14 >= 256 )
      goto LABEL_17;
  }
  v16 = a1 + 40LL * v9;
  *(_DWORD *)(v16 + 48) = v5[1].LowPart;
  *(_QWORD *)(v16 + 24) = v7;
  *(_QWORD *)(v16 + 32) = v12;
  *(_QWORD *)(v16 + 40) = v11;
  *(_QWORD *)(v16 + 56) = PsGetCurrentProcessId();
LABEL_17:
  if ( v9 == 256 )
    return 3221225473LL;
  DbgPrint_Stub("Mapped %d bytes at %X to %X", v5[1].LowPart, (_DWORD)v7, (_DWORD)v12);
  return 0;
}
// 140001590: using guessed type __int64 sub_140001590(const char *, ...);

//----- (0000000140001CD0) ----------------------------------------------------
__int64 __fastcall DispatchTable(__int64 a1, __int64 a2)
{
  __int64 v2; // rbp
  __int64 v3; // r14
  __int64 v5; // r13
  unsigned int v6; // ebx
  unsigned __int16 v7; // dx
  char v8; // al
  unsigned __int32 v9; // eax
  unsigned __int16 v10; // ax
  unsigned __int8 v11; // al
  char v12; // r8
  __int64 v13; // rcx
  int v14; // eax
  __int64 v15; // r12
  int v16; // r15d
  __int64 v17; // rbx
  __int64 i; // rdi
  __int64 v19; // rbx
  unsigned int v20; // edi
  int v21; // ecx
  _BYTE *v22; // rax
  unsigned int v23; // edi
  int v24; // ecx
  __int64 v25; // r15
  _BYTE *v26; // rcx
  unsigned __int8 v27; // di
  _QWORD *v28; // r9
  ULONG BusDataByOffset; // ecx
  int v30; // eax
  unsigned __int8 v31; // dl
  unsigned __int64 *v32; // rax
  int v33; // edi
  ULONG v34; // edx
  ULONG v35; // eax
  int v36; // ecx
  ULONG Length; // [rsp+28h] [rbp-40h]
  unsigned __int64 Offset; // [rsp+30h] [rbp-38h]
  int Buffer; // [rsp+38h] [rbp-30h] BYREF

  v2 = *(_QWORD *)(a2 + 184);
  v3 = 0;
  v5 = *(_QWORD *)(a1 + 64);
  v6 = -1073741823;
  switch ( *(_DWORD *)(v2 + 24) )
  {
    case 0x80006430:
      if ( *(_DWORD *)(v2 + 16) != 2 )
      {
        *(_QWORD *)(a2 + 56) = 2;
        goto LABEL_85;
      }
      v7 = **(_WORD **)(a2 + 24);
      v8 = *(_BYTE *)(v2 + 8);
      switch ( v8 )
      {
        case 1:
          v11 = __inbyte(v7);
          v6 = 0;
          **(_BYTE **)(a2 + 24) = v11;
          break;
        case 2:
          v10 = __inword(v7);
          v6 = 0;
          **(_WORD **)(a2 + 24) = v10;
          break;
        case 4:
          v9 = __indword(v7);
          v6 = 0;
          **(_DWORD **)(a2 + 24) = v9;
          break;
        default:
          goto LABEL_85;
      }
      goto LABEL_86;
    case 0x80006434:
      if ( *(_DWORD *)(v2 + 8) )
        goto LABEL_84;
      v12 = *(_BYTE *)(v2 + 16);
      if ( ((v12 - 5) & 0xFC) != 0 || v12 == 7 )
        goto LABEL_85;
      v13 = *(_QWORD *)(a2 + 24);
      if ( v12 == 5 )
      {
        __outbyte(*(_WORD *)v13, *(_BYTE *)(v13 + 4));
      }
      else if ( v12 == 6 )
      {
        __outword(*(_WORD *)v13, *(_WORD *)(v13 + 4));
      }
      if ( v12 == 8 )
        __outdword(*(_WORD *)v13, *(_DWORD *)(v13 + 4));
      v6 = 0;
      goto LABEL_86;
    case 0x80006448:
      v6 = IoctlReadMsr(v2, a2);
      goto LABEL_86;
    case 0x8000644C:
      v6 = IoctlWriteMsr(v2, a2);
      goto LABEL_86;
    case 0x8000645C:
      v6 = IoctlMapPhysicalMemory(v5, v2, a2);
      goto LABEL_86;
    case 0x80006460:
      if ( *(_DWORD *)(v2 + 8) )
        goto LABEL_85;
      v14 = *(_DWORD *)(v2 + 16);
      if ( v14 == 4 )
      {
        v15 = **(unsigned int **)(a2 + 24);
      }
      else
      {
        if ( v14 != 8 )
          goto LABEL_85;
        v15 = **(_QWORD **)(a2 + 24);
      }
      v16 = 0;
      v17 = v5 + 32;
      for ( i = 0; i < 256; ++i )
      {
        if ( *(_DWORD *)(v17 + 16) && *(_QWORD *)v17 == v15 && *(HANDLE *)(v17 + 24) == PsGetCurrentProcessId() )
          break;
        ++v16;
        v17 += 40;
      }
      if ( v16 == 256 )
      {
        v6 = -1073741811;
      }
      else
      {
        v19 = v5 + 40LL * v16;
        DbgPrint_Stub("Releasing %d bytes at %X", *(_DWORD *)(v19 + 48), v15);
        MmUnmapLockedPages(*(PVOID *)(v19 + 32), *(PMDL *)(v19 + 40));
        MmUnmapIoSpace(*(PVOID *)(v19 + 24), *(unsigned int *)(v19 + 48));
        IoFreeMdl(*(PMDL *)(v19 + 40));
        *(_DWORD *)(v19 + 48) = 0;
        v6 = 0;
      }
      goto LABEL_86;
    case 0x80006494:
      if ( *(_DWORD *)(v2 + 16) )
        goto LABEL_84;
      if ( *(_DWORD *)(v2 + 8) == 4 )
      {
        v6 = 0;
        **(_DWORD **)(a2 + 24) = *(_DWORD *)(v5 + 8);
      }
      else
      {
        *(_QWORD *)(a2 + 56) = 4;
        v6 = -1073741811;
      }
      goto LABEL_86;
    case 0x80006498:
      if ( *(_DWORD *)(v2 + 16) != 8 )
      {
        *(_QWORD *)(a2 + 56) = 8;
        goto LABEL_85;
      }
      v20 = *(unsigned __int8 *)(v2 + 8);
      if ( (unsigned __int8)v20 > 8u )
        goto LABEL_85;
      v21 = 278;
      if ( !_bittest(&v21, v20) )
        goto LABEL_85;
      v22 = MmMapIoSpace(**(PHYSICAL_ADDRESS **)(a2 + 24), (unsigned __int8)v20, MmNonCached);
      if ( v22 )
      {
        if ( (_BYTE)v20 == 1 )
        {
          **(_BYTE **)(a2 + 24) = *v22;
          MmUnmapIoSpace(v22, 1u);
          v6 = 0;
        }
        else if ( (_BYTE)v20 == 2 )
        {
          **(_WORD **)(a2 + 24) = *(_WORD *)v22;
          MmUnmapIoSpace(v22, 2u);
          v6 = 0;
        }
        else if ( (_BYTE)v20 == 4 )
        {
          **(_DWORD **)(a2 + 24) = *(_DWORD *)v22;
          MmUnmapIoSpace(v22, 4u);
          v6 = 0;
        }
        else
        {
          if ( (_BYTE)v20 == 8 )
            **(_QWORD **)(a2 + 24) = *(_QWORD *)v22;
          MmUnmapIoSpace(v22, (unsigned __int8)v20);
          v6 = 0;
        }
      }
      goto LABEL_86;
    case 0x8000649C:
      if ( *(_DWORD *)(v2 + 8) )
        goto LABEL_84;
      v23 = *(unsigned __int8 *)(v2 + 16);
      LOBYTE(v23) = v23 - 8;
      if ( (unsigned __int8)v23 > 8u )
        goto LABEL_85;
      v24 = 278;
      if ( !_bittest(&v24, v23) )
        goto LABEL_85;
      v25 = *(_QWORD *)(a2 + 24);
      v26 = MmMapIoSpace(*(PHYSICAL_ADDRESS *)v25, (unsigned __int8)v23, MmNonCached);
      if ( v26 )
      {
        if ( (_BYTE)v23 == 1 )
        {
          *v26 = *(_BYTE *)(v25 + 8);
          MmUnmapIoSpace(v26, 1u);
          v6 = 0;
        }
        else if ( (_BYTE)v23 == 2 )
        {
          *(_WORD *)v26 = *(_WORD *)(v25 + 8);
          MmUnmapIoSpace(v26, 2u);
          v6 = 0;
        }
        else if ( (_BYTE)v23 == 4 )
        {
          *(_DWORD *)v26 = *(_DWORD *)(v25 + 8);
          MmUnmapIoSpace(v26, 4u);
          v6 = 0;
        }
        else
        {
          if ( (_BYTE)v23 == 8 )
            *(_QWORD *)v26 = *(_QWORD *)(v25 + 8);
          MmUnmapIoSpace(v26, (unsigned __int8)v23);
          v6 = 0;
        }
      }
      goto LABEL_86;
    case 0x800064A0:
      if ( *(_DWORD *)(v2 + 16) != 8 )
      {
        *(_QWORD *)(a2 + 56) = 8;
        goto LABEL_85;
      }
      v27 = *(_BYTE *)(v2 + 8);
      if ( !v27 )
        goto LABEL_85;
      v28 = *(_QWORD **)(a2 + 24);
      BusDataByOffset = HalGetBusDataByOffset(
                          PCIConfiguration,
                          (unsigned __int8)*v28,
                          (*v28 >> 8) & 0x1F | (32 * ((*v28 >> 16) & 7)),
                          v28,
                          HIDWORD(*v28),
                          v27);
      if ( BusDataByOffset )
      {
        if ( v27 == 2 || BusDataByOffset != 2 )
        {
          v30 = 0;
          if ( v27 != BusDataByOffset )
            v30 = -1073741823;
          v6 = v30;
        }
        else
        {
          v6 = -1073741632;
        }
      }
      else
      {
        v6 = -1073741275;
      }
      goto LABEL_86;
    case 0x800064A4:
      if ( *(_DWORD *)(v2 + 8) )
      {
LABEL_84:
        *(_QWORD *)(a2 + 56) = 0;
LABEL_85:
        v6 = -1073741306;
        goto LABEL_86;
      }
      v31 = *(_BYTE *)(v2 + 16) - 8;
      if ( ((*(_BYTE *)(v2 + 16) - 9) & 0xFC) != 0 || *(_BYTE *)(v2 + 16) == 11 )
        goto LABEL_85;
      v32 = *(unsigned __int64 **)(a2 + 24);
      v33 = v31;
      Length = v31;
      Offset = *v32;
      v34 = (unsigned __int8)*v32;
      Buffer = *((_DWORD *)v32 + 2);
      v35 = HalSetBusDataByOffset(
              PCIConfiguration,
              v34,
              (Offset >> 8) & 0x1F | (32 * ((Offset >> 16) & 7)),
              &Buffer,
              HIDWORD(Offset),
              Length);
      v36 = 0;
      if ( v35 != v33 )
        v36 = -1073741823;
      v6 = v36;
LABEL_86:
      *(_DWORD *)(a2 + 48) = v6;
      if ( !v6 )
        v3 = *(unsigned int *)(v2 + 8);
      *(_QWORD *)(a2 + 56) = v3;
      IofCompleteRequest((PIRP)a2, 0);
      return v6;
    default:
      goto LABEL_86;
  }
}
// 140001590: using guessed type __int64 sub_140001590(const char *, ...);
// 140001A90: using guessed type __int64 __fastcall sub_140001A90(_QWORD, _QWORD);
// 140001B00: using guessed type __int64 __fastcall sub_140001B00(_QWORD, _QWORD);
// 140001B50: using guessed type __int64 __fastcall sub_140001B50(_QWORD, _QWORD, _QWORD);

//----- (0000000140006000) ----------------------------------------------------
PVOID WdmlibInit()
{
  PVOID SystemRoutineAddress; // rax
  PVOID result; // rax
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-18h] BYREF

  RtlInitUnicodeString(&DestinationString, L"IoCreateDeviceSecure");
  SystemRoutineAddress = MmGetSystemRoutineAddress(&DestinationString);
  if ( !SystemRoutineAddress )
    SystemRoutineAddress = IoDevObjCreateDeviceSecure;
  qword_1400041E8 = (__int64)SystemRoutineAddress;
  RtlInitUnicodeString(&DestinationString, L"IoValidateDeviceIoControlAccess");
  result = MmGetSystemRoutineAddress(&DestinationString);
  byte_1400041E0 = 1;
  qword_1400041F0 = (__int64)result;
  return result;
}
// 1400041E0: using guessed type char byte_1400041E0;
// 1400041E8: using guessed type __int64 qword_1400041E8;
// 1400041F0: using guessed type __int64 qword_1400041F0;

//----- (0000000140006068) ----------------------------------------------------
NTSTATUS __stdcall WdmlibIoCreateDeviceSecure(
        PDRIVER_OBJECT DriverObject,
        ULONG DeviceExtensionSize,
        PUNICODE_STRING DeviceName,
        ULONG DeviceType,
        ULONG DeviceCharacteristics,
        BOOLEAN Exclusive,
        PCUNICODE_STRING DefaultSDDLString,
        LPCGUID DeviceClassGuid,
        PDEVICE_OBJECT *DeviceObject)
{
  if ( !byte_1400041E0 )
    WdmlibInit();
  return qword_1400041E8(
           DriverObject,
           DeviceExtensionSize,
           DeviceName,
           DeviceType,
           DeviceCharacteristics,
           Exclusive,
           DefaultSDDLString,
           DeviceClassGuid,
           DeviceObject);
}
// 1400041E8: invalid function type '?' has been ignored
// 1400041E0: using guessed type char byte_1400041E0;
// 1400041E8: using guessed type NTSTATUS (__fastcall *qword_1400041E8)(_QWORD, _QWORD, _QWORD, _QWORD, _DWORD, _DWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001400060F8) ----------------------------------------------------
__int64 __fastcall IopDevObjApplyPostCreationSettings(PVOID Object)
{
  __int64 v1; // rdx
  __int64 v2; // rbx
  __int64 result; // rax
  unsigned int v5; // ebx
  HANDLE Handle; // [rsp+40h] [rbp-18h] BYREF
  SECURITY_INFORMATION SecurityInformation; // [rsp+70h] [rbp+18h]
  ACCESS_MASK DesiredAccess; // [rsp+78h] [rbp+20h] BYREF

  v2 = v1;
  if ( (*(_BYTE *)v1 & 2) == 0 )
    return 0;
  result = SeUtilSecurityInfoFromSecurityDescriptor(*(PSECURITY_DESCRIPTOR *)(v1 + 8));
  if ( (int)result >= 0 )
  {
    SeSetSecurityAccessMask(SecurityInformation, &DesiredAccess);
    LODWORD(result) = ObOpenObjectByPointer(Object, 0x200u, nullptr, DesiredAccess, IoDeviceObjectType, 0, &Handle);
    if ( (int)result >= 0 )
    {
      v5 = ZwSetSecurityObject(Handle, SecurityInformation, *(PSECURITY_DESCRIPTOR *)(v2 + 8));
      ZwClose(Handle);
      return v5;
    }
  }
  return result;
}
// 140006105: variable 'v1' is possibly undefined

//----- (000000014000619C) ----------------------------------------------------
__int64 __usercall IoDevObjCreateDeviceSecure@<rax>(
        PDRIVER_OBJECT DriverObject@<rcx>,
        ULONG DeviceExtensionSize@<edx>,
        PUNICODE_STRING DeviceName@<r8>,
        int a4,
        char a5,
        __int64 a6,
        __int64 a7,
        PDEVICE_OBJECT DeviceObject)
{
  ULONG v8; // r9d
  PDEVICE_OBJECT v9; // rsi
  ULONG DeviceCharacteristics; // ebp
  ULONG v11; // r14d
  __int64 result; // rax
  char v16; // al
  int updated; // ebx
  BOOLEAN Exclusive; // cl
  ULONG v19[5]; // [rsp+40h] [rbp-58h] BYREF
  BOOLEAN v20; // [rsp+54h] [rbp-44h]
  _BYTE v21[24]; // [rsp+58h] [rbp-40h] BYREF
  __int64 v22; // [rsp+B0h] [rbp+18h] BYREF

  v9 = DeviceObject;
  DeviceObject = nullptr;
  DeviceCharacteristics = a4;
  *(_QWORD *)&v9->Type = 0;
  v11 = v8;
  if ( !DeviceName && (DeviceCharacteristics & 0x80u) == 0 )
    return 3221225485LL;
  if ( !a7 )
  {
    PpRegStateInitEmptyCreationSettings((__int64)v19);
LABEL_8:
    v16 = v19[0];
    if ( (v19[0] & 2) == 0 )
    {
      updated = SeSddlSecurityDescriptorFromSDDL((unsigned __int16 *)a6, 1u, &v22);
      if ( updated < 0
        || (PpRegStateLoadSecurityDescriptor(v22, (__int64)v19), a7)
        && (PpRegStateInitEmptyCreationSettings((__int64)v21),
            PpRegStateLoadSecurityDescriptor(v22, (__int64)v21),
            updated = PpRegStateUpdateStackCreationSettings((unsigned int *)a7, (__int64)v21),
            updated < 0) )
      {
$Exit$30769:
        PpRegStateFreeStackCreationSettings((__int64)v19);
        return (unsigned int)updated;
      }
      v16 = v19[0];
    }
    Exclusive = a5;
    if ( (v16 & 1) != 0 )
      v11 = v19[1];
    if ( (v16 & 4) != 0 )
      DeviceCharacteristics = v19[4];
    if ( (v16 & 8) != 0 )
      Exclusive = v20;
    updated = IoCreateDevice(
                DriverObject,
                DeviceExtensionSize,
                DeviceName,
                v11,
                DeviceCharacteristics,
                Exclusive,
                &DeviceObject);
    if ( updated >= 0 )
    {
      updated = IopDevObjApplyPostCreationSettings(DeviceObject);
      if ( updated >= 0 )
        *(_QWORD *)&v9->Type = DeviceObject;
      else
        IoDeleteDevice(DeviceObject);
    }
    goto $Exit$30769;
  }
  LODWORD(result) = PpRegStateReadCreateClassCreationSettings((unsigned int *)a7, (__int64)DriverObject, (__int64)v19);
  if ( (int)result >= 0 )
    goto LABEL_8;
  return result;
}
// 1400061CC: variable 'v8' is possibly undefined

//----- (000000014000634C) ----------------------------------------------------
void __fastcall PpRegStateLoadSecurityDescriptor(__int64 a1, __int64 a2)
{
  *(_DWORD *)a2 = 2;
  *(_QWORD *)(a2 + 8) = a1;
}

//----- (0000000140006358) ----------------------------------------------------
void __fastcall PpRegStateFreeStackCreationSettings(__int64 a1)
{
  if ( (*(_BYTE *)a1 & 2) != 0 )
    ExFreePoolWithTag(*(PVOID *)(a1 + 8), 0);
}

//----- (0000000140006374) ----------------------------------------------------
int __fastcall PiRegStateOpenClassKey(unsigned int *a1, ACCESS_MASK a2, int a3, int *a4, _QWORD *a5)
{
  int result; // eax
  NTSTATUS v10; // eax
  int v11; // ebx
  int v12; // [rsp+70h] [rbp-B8h] BYREF
  HANDLE Handle; // [rsp+78h] [rbp-B0h] BYREF
  _QWORD v14[2]; // [rsp+80h] [rbp-A8h] BYREF
  wchar_t Dest[40]; // [rsp+90h] [rbp-98h] BYREF

  *a5 = 0;
  if ( a4 )
    *a4 = 0;
  result = CmRegUtilOpenExistingWstrKey(
             nullptr,
             L"\\Registry\\Machine\\System\\CurrentControlSet\\Control\\Class",
             0x20019u,
             &Handle);
  if ( result >= 0 )
  {
    snwprintf(
      Dest,
      0x27u,
      L"{%08X-%04X-%04X-%02X%02X-%02X%02X%02X%02X%02X%02X}",
      *a1,
      *((unsigned __int16 *)a1 + 2),
      *((unsigned __int16 *)a1 + 3),
      *((unsigned __int8 *)a1 + 8),
      *((unsigned __int8 *)a1 + 9),
      *((unsigned __int8 *)a1 + 10),
      *((unsigned __int8 *)a1 + 11),
      *((unsigned __int8 *)a1 + 12),
      *((unsigned __int8 *)a1 + 13),
      *((unsigned __int8 *)a1 + 14),
      *((unsigned __int8 *)a1 + 15));
    Dest[38] = 0;
    if ( a3 )
    {
      v10 = CmRegUtilCreateWstrKey(Handle, Dest, a2, 0, nullptr, &v12, v14);
    }
    else
    {
      v10 = CmRegUtilOpenExistingWstrKey(Handle, Dest, a2, v14);
      v12 = 2;
    }
    v11 = v10;
    ZwClose(Handle);
    if ( v11 >= 0 )
    {
      *a5 = v14[0];
      if ( a4 )
        *a4 = v12;
    }
    return v11;
  }
  return result;
}
// 1400035F0: using guessed type wchar_t aRegistryMachin[57];

//----- (000000014000650C) ----------------------------------------------------
__int64 __fastcall PpRegStateInitEmptyCreationSettings(__int64 a1)
{
  *(_DWORD *)a1 = 0;
  *(_QWORD *)(a1 + 8) = 0;
  *(_DWORD *)(a1 + 4) = 0;
  *(_DWORD *)(a1 + 16) = 0;
  *(_DWORD *)(a1 + 20) = 0;
  return 0;
}

//----- (0000000140006520) ----------------------------------------------------
__int64 __fastcall PiRegStateReadStackCreationSettingsFromKey(void *a1, __int64 a2)
{
  int FullBuffer; // eax
  __int64 v5; // r9
  int v6; // ebx
  PVOID v7; // rax
  int Dword; // eax
  int v9; // eax
  int v10; // eax
  void *v11; // rcx
  PVOID P[9]; // [rsp+30h] [rbp-48h] BYREF
  char v14; // [rsp+88h] [rbp+10h]
  PVOID SecurityDescriptor; // [rsp+98h] [rbp+20h] BYREF

  *(_DWORD *)a2 = 0;
  *(_QWORD *)(a2 + 8) = 0;
  *(_DWORD *)(a2 + 4) = 0;
  *(_DWORD *)(a2 + 16) = 0;
  *(_DWORD *)(a2 + 20) = 0;
  P[0] = nullptr;
  FullBuffer = CmRegUtilWstrValueGetFullBuffer(a1, (__int64)P);
  v6 = FullBuffer;
  if ( FullBuffer < 0 )
  {
    if ( FullBuffer == -1073741772 )
    {
      SecurityDescriptor = nullptr;
      v6 = 0;
    }
  }
  else
  {
    LOBYTE(v5) = 1;
    v6 = SeCaptureSecurityDescriptor((char *)P[0] + *((unsigned int *)P[0] + 2), 0, 1, v5, &SecurityDescriptor);
  }
  if ( P[0] )
    ExFreePoolWithTag(P[0], 0);
  if ( v6 < 0 )
    goto $ErrorExit$30792;
  if ( SecurityDescriptor )
  {
    v6 = SeUtilSecurityInfoFromSecurityDescriptor(SecurityDescriptor);
    if ( v6 < 0 )
      goto $ErrorExit$30792;
    if ( v14 )
    {
      ExFreePoolWithTag(SecurityDescriptor, 0);
    }
    else
    {
      v7 = SecurityDescriptor;
      *(_DWORD *)a2 |= 2u;
      *(_QWORD *)(a2 + 8) = v7;
    }
  }
  Dword = CmRegUtilWstrValueGetDword(a1, L"DeviceType", 0, (_DWORD *)(a2 + 4));
  v6 = Dword;
  if ( Dword < 0 )
  {
    if ( Dword != -1073741772 )
      goto $ErrorExit$30792;
  }
  else
  {
    *(_DWORD *)a2 |= 1u;
  }
  v9 = CmRegUtilWstrValueGetDword(a1, L"DeviceCharacteristics", 0, (_DWORD *)(a2 + 16));
  v6 = v9;
  if ( v9 < 0 )
  {
    if ( v9 != -1073741772 )
      goto $ErrorExit$30792;
  }
  else
  {
    *(_DWORD *)a2 |= 4u;
  }
  v10 = CmRegUtilWstrValueGetDword(a1, L"Exclusive", 0, (_DWORD *)(a2 + 20));
  v6 = v10;
  if ( v10 >= 0 )
  {
    *(_DWORD *)a2 |= 8u;
    return (unsigned int)v6;
  }
  if ( v10 == -1073741772 )
    return 0;
$ErrorExit$30792:
  v11 = *(void **)(a2 + 8);
  if ( v11 )
    ExFreePoolWithTag(v11, 0);
  *(_DWORD *)a2 = 0;
  *(_QWORD *)(a2 + 8) = 0;
  *(_DWORD *)(a2 + 4) = 0;
  *(_DWORD *)(a2 + 16) = 0;
  *(_DWORD *)(a2 + 20) = 0;
  return (unsigned int)v6;
}
// 14000659F: variable 'v5' is possibly undefined
// 140003108: using guessed type __int64 __fastcall SeCaptureSecurityDescriptor(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 140003588: using guessed type wchar_t aDevicetype[11];
// 1400035A0: using guessed type wchar_t aDevicecharacte[22];
// 1400035D0: using guessed type wchar_t aExclusive[10];

//----- (00000001400066E4) ----------------------------------------------------
int __fastcall PpRegStateReadCreateClassCreationSettings(unsigned int *a1, __int64 a2, __int64 a3)
{
  int result; // eax
  int v6; // ebx
  int StackCreationSettingsFromKey; // eax
  void *v8; // rcx
  HANDLE v9; // rdi
  void *v10; // [rsp+30h] [rbp-18h] BYREF
  _BYTE v11[8]; // [rsp+60h] [rbp+18h] BYREF
  HANDLE Handle; // [rsp+68h] [rbp+20h] BYREF

  *(_DWORD *)a3 = 0;
  *(_QWORD *)(a3 + 8) = 0;
  *(_DWORD *)(a3 + 4) = 0;
  *(_DWORD *)(a3 + 16) = 0;
  *(_DWORD *)(a3 + 20) = 0;
  Handle = nullptr;
  v10 = nullptr;
  result = PiRegStateOpenClassKey(a1, 0xF003Fu, 1, (int *)v11, &Handle);
  if ( result >= 0 )
  {
    if ( *(_DWORD *)v11 == 2 )
    {
      v6 = CmRegUtilOpenExistingWstrKey(Handle, L"Properties", 0x20019u, &v10);
      ZwClose(Handle);
      if ( v6 < 0 )
      {
        if ( v6 == -1073741772 )
          return 0;
        return v6;
      }
      StackCreationSettingsFromKey = PiRegStateReadStackCreationSettingsFromKey(v10, a3);
      v8 = v10;
      v6 = StackCreationSettingsFromKey;
    }
    else
    {
      v9 = Handle;
      if ( *(_QWORD *)(a2 + 48) == -24 )
      {
        v6 = -1073741670;
      }
      else
      {
        v6 = CmRegUtilWstrValueSetUcString(Handle);
        if ( v6 >= 0 )
        {
          wcscpy((wchar_t *)v11, L"1");
          v6 = CmRegUtilWstrValueSetWstrString(v9, L"NoDisplayClass", (PCWSTR)v11);
          if ( v6 >= 0 )
            v6 = CmRegUtilWstrValueSetWstrString(v9, L"NoUseClass", (PCWSTR)v11);
        }
      }
      v8 = v9;
    }
    ZwClose(v8);
    return v6;
  }
  return result;
}
// 140003510: using guessed type wchar_t aProperties[11];

//----- (000000014000680C) ----------------------------------------------------
int __fastcall PpRegStateUpdateStackCreationSettings(unsigned int *a1, __int64 a2)
{
  int result; // eax
  __int64 v4; // r9
  int v5; // eax
  void *v6; // rbx
  int WstrKey; // ebx
  ULONG v8; // eax
  HANDLE KeyHandle[3]; // [rsp+40h] [rbp-18h] BYREF
  PVOID P; // [rsp+70h] [rbp+18h] BYREF
  HANDLE Handle; // [rsp+78h] [rbp+20h] BYREF

  result = PiRegStateOpenClassKey(a1, 0xF003Fu, 0, nullptr, &Handle);
  if ( result >= 0 )
  {
    v5 = dword_1400041F8;
    v6 = &unk_140004000;
    if ( !dword_1400041F8 )
    {
      LOBYTE(v4) = 1;
      if ( (int)SeCaptureSecurityDescriptor(&unk_140004000, 0, 1, v4, &P) < 0 )
      {
        v5 = 2;
        dword_1400041F8 = 2;
      }
      else
      {
        dword_1400041F8 = 1;
        ExFreePoolWithTag(P, 0);
        v5 = dword_1400041F8;
      }
    }
    if ( v5 != 1 )
      v6 = nullptr;
    P = v6;
    WstrKey = CmRegUtilCreateWstrKey(Handle, L"Properties", 0xF003Fu, 0, v6, nullptr, KeyHandle);
    ZwClose(Handle);
    if ( WstrKey >= 0 )
    {
      v8 = RtlLengthSecurityDescriptor(*(PSECURITY_DESCRIPTOR *)(a2 + 8));
      WstrKey = CmRegUtilWstrValueSetFullBuffer(KeyHandle[0], v8);
      ZwClose(KeyHandle[0]);
    }
    return WstrKey;
  }
  return result;
}
// 140006868: variable 'v4' is possibly undefined
// 140003108: using guessed type __int64 __fastcall SeCaptureSecurityDescriptor(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 140003510: using guessed type wchar_t aProperties[11];
// 1400041F8: using guessed type int dword_1400041F8;

//----- (0000000140006930) ----------------------------------------------------
__int64 __fastcall SepSddlParseWideStringUlong(unsigned __int16 *a1, unsigned __int16 **a2, unsigned int *a3)
{
  unsigned __int16 *v5; // r10
  unsigned __int16 *v6; // r9
  bool v7; // cf
  int v8; // edx
  unsigned int v9; // r8d
  int v10; // ecx
  unsigned __int16 v11; // ax

  *a3 = 0;
  *a2 = a1;
  v5 = a1;
  v6 = a1;
  v7 = *a1 < 0x30u;
  if ( *a1 != 48 )
  {
LABEL_6:
    if ( !v7 )
    {
      v8 = 10;
      if ( *a1 <= 0x39u )
        goto LABEL_9;
    }
    goto LABEL_8;
  }
  if ( a1[1] != 120 && a1[1] != 88 )
  {
    v7 = *a1 < 0x30u;
    goto LABEL_6;
  }
  v5 = a1 + 2;
  v6 = a1 + 2;
LABEL_8:
  v8 = 16;
LABEL_9:
  v9 = 0;
  while ( 1 )
  {
    v11 = *v6;
    if ( !*v6 )
      break;
    if ( v11 < 0x30u || v11 > 0x39u )
    {
      if ( v8 != 16 )
        break;
      if ( v11 < 0x41u || v11 > 0x46u )
      {
        if ( v11 < 0x61u || v11 > 0x66u )
          break;
        v10 = v11 - 87;
      }
      else
      {
        v10 = v11 - 55;
      }
    }
    else
    {
      v10 = v11 - 48;
    }
    if ( v10 + v8 * v9 < v9 )
      return 0;
    v9 = v10 + v8 * v9;
    ++v6;
  }
  if ( v6 != v5 )
  {
    *a2 = v6;
    *a3 = v9;
    return 1;
  }
  return 0;
}

//----- (0000000140006A0C) ----------------------------------------------------
// local variable allocation has failed, the output may be wrong!
__int64 __fastcall SepSddlAddAceToAcl(int a1, int a2, int a3, int a4, ACCESS_MASK AccessMask, int a6, PSID Sid)
{
  struct _ACL *v7; // rdi
  size_t v8; // r12
  const void **v9; // r14
  _DWORD *v10; // rsi
  ULONG v11; // ebx
  int v12; // ebp
  unsigned int v13; // ebx
  struct _ACL *PoolWithTag; // rax
  struct _ACL *v15; // r13
  __int64 result; // rax

  v7 = **(struct _ACL ***)&a1;
  v8 = (unsigned int)**(_DWORD **)&a2;
  v9 = *(const void ***)&a1;
  v10 = *(_DWORD **)&a2;
  v11 = RtlLengthSid(Sid) + 8;
  v12 = v11 + v8;
  if ( v11 + (unsigned int)v8 > v7->AclSize )
  {
    v13 = v8 + a6 * v11;
    PoolWithTag = (struct _ACL *)ExAllocatePoolWithTag(PagedPool, v13, 0x6C416553u);
    v15 = PoolWithTag;
    if ( !PoolWithTag )
      return 3221225626LL;
    memset(PoolWithTag, 0, v13);
    memmove(v15, *v9, v8);
    v15->AclSize = v13;
    ExFreePoolWithTag(v7, 0);
    *v9 = v15;
    v7 = v15;
  }
  *v10 = v12;
  LODWORD(result) = RtlAddAccessAllowedAce(v7, 2u, AccessMask, Sid);
  return result;
}
// 140006A0C: variables would overlap: edx.4 and rdx.8
// 140006A0C: variables would overlap: ecx.4 and rcx.8

//----- (0000000140006AEC) ----------------------------------------------------
__int64 __fastcall SepSddlLookupAccessMaskInTable(wchar_t *Str1)
{
  _DWORD *v1; // rdx
  wchar_t **v2; // r8
  wchar_t **v3; // rbp
  _DWORD *v4; // r12
  unsigned int v6; // ebx
  wchar_t **i; // rdi

  v3 = v2;
  v4 = v1;
  v6 = 0;
  for ( i = &off_140004150; wcsnicmp(Str1, *i, *((unsigned int *)i + 2)); i += 2 )
  {
    if ( ++v6 >= 8 )
    {
      *v4 = 0;
      *v3 = Str1;
      return 0;
    }
  }
  *v4 = *((_DWORD *)&off_140004150 + 4 * v6 + 3);
  *v3 = &Str1[*((unsigned int *)&off_140004150 + 4 * v6 + 2)];
  return 1;
}
// 140006B0B: variable 'v2' is possibly undefined
// 140006B0E: variable 'v1' is possibly undefined
// 140004150: using guessed type wchar_t *off_140004150;

//----- (0000000140006B80) ----------------------------------------------------
__int64 __fastcall SepSddlGetSidForString(wchar_t *Str1)
{
  _QWORD *v1; // rdx
  _QWORD *v2; // r8
  _QWORD *v3; // r12
  _QWORD *v4; // rbx
  __int64 v6; // rdi
  unsigned int *i; // rsi
  __int64 v9; // rdi

  v3 = v2;
  v4 = v1;
  v6 = 0;
  for ( i = (unsigned int *)&unk_140004044; wcsnicmp(Str1, (const wchar_t *)&unk_140004030 + 12 * v6 + 6, *i); i += 6 )
  {
    v6 = (unsigned int)(v6 + 1);
    if ( (unsigned int)v6 >= 0xC )
    {
      *v4 = 0;
      return 3221225587LL;
    }
  }
  v9 = 3 * v6;
  *v3 = &Str1[*((unsigned int *)&unk_140004030 + 2 * v9 + 5)];
  if ( *((_DWORD *)&unk_140004030 + 2 * v9 + 2) != 1 || IoIsWdmVersionAvailable(1u, 0x20u) )
    *v4 = *(LUID *)((char *)&SeExports->SeCreateTokenPrivilege + *((_QWORD *)&unk_140004030 + v9));
  else
    *v4 = 0;
  return 0;
}
// 140006B98: variable 'v2' is possibly undefined
// 140006B9B: variable 'v1' is possibly undefined

//----- (0000000140006C40) ----------------------------------------------------
// local variable allocation has failed, the output may be wrong!
__int64 __fastcall SepSddlGetAclForString(wchar_t *Str1, int a2)
{
  wchar_t **v2; // r8
  PVOID *v3; // r13
  wchar_t **v4; // rbp
  wchar_t *v5; // rbx
  unsigned int SidForString; // esi
  unsigned int v7; // r12d
  wchar_t *v8; // rax
  __int64 v10; // rcx
  wchar_t *v11; // rdi
  bool v12; // zf
  wchar_t *v13; // rax
  int v14; // edi
  wchar_t *i; // rax
  unsigned int v16; // r14d
  _QWORD *PoolWithTag; // rax
  unsigned int v18; // ebp
  PVOID v19; // rax
  int v20; // r12d
  unsigned int v21; // ebp
  unsigned __int16 *j; // rbx
  __int64 v23; // rax
  unsigned __int16 *v24; // rax
  _WORD *v25; // rbx
  _WORD *v26; // [rsp+40h] [rbp-58h]
  unsigned int v27; // [rsp+A0h] [rbp+8h] BYREF
  int v28; // [rsp+A8h] [rbp+10h]
  int v29; // [rsp+B0h] [rbp+18h]
  unsigned __int16 *v30; // [rsp+B8h] [rbp+20h] BYREF

  v3 = *(PVOID **)&a2;
  v4 = v2;
  **(_QWORD **)&a2 = 0;
  v5 = Str1;
  SidForString = 0;
  v7 = 0;
  v8 = wcschr(Str1, 0x3Au);
  *v4 = v8;
  if ( v8 == v5 )
    return 3221225485LL;
  if ( v8 )
  {
    v13 = v8 - 1;
  }
  else
  {
    v10 = -1;
    v11 = v5;
    do
    {
      if ( !v10 )
        break;
      v12 = *v11++ == 0;
      --v10;
    }
    while ( !v12 );
    v13 = &v5[-v10 - 2];
  }
  *v4 = v13;
  v14 = 0;
  for ( i = v5; i < *v4; ++i )
  {
    if ( *i == 59 )
    {
      ++v7;
    }
    else if ( *i != 32 )
    {
      v14 = 1;
    }
  }
  v16 = v7 / 5;
  if ( v7 != 5 * (v7 / 5) || !v7 && v14 )
    return (unsigned int)-1073741811;
  if ( !v16 )
  {
    PoolWithTag = ExAllocatePoolWithTag(PagedPool, 8u, 0x6C416553u);
    *v3 = PoolWithTag;
    if ( PoolWithTag )
    {
      *PoolWithTag = 0;
      *(_BYTE *)*v3 = 2;
      *((_BYTE *)*v3 + 1) = 0;
      *((_WORD *)*v3 + 1) = 8;
      *((_WORD *)*v3 + 2) = 0;
      *((_WORD *)*v3 + 3) = 0;
      return SidForString;
    }
    return (unsigned int)-1073741670;
  }
  v18 = 48 * v16 + 8;
  if ( v18 > 0xFFFF )
    v18 = 0xFFFF;
  v19 = ExAllocatePoolWithTag(PagedPool, v18, 0x6C416553u);
  *v3 = v19;
  if ( !v19 )
    return (unsigned int)-1073741670;
  v28 = 8;
  memset(v19, 0, v18);
  *(_BYTE *)*v3 = 2;
  v20 = 0;
  *((_BYTE *)*v3 + 1) = 0;
  *((_WORD *)*v3 + 1) = v18;
  *((_WORD *)*v3 + 2) = 0;
  *((_WORD *)*v3 + 3) = 0;
  while ( 1 )
  {
    v21 = 0;
    v27 = 0;
    while ( *v5 == 32 )
      ++v5;
    if ( *v5 == 40 )
LABEL_30:
      ++v5;
    if ( *v5 == 32 )
      goto LABEL_30;
    if ( wcsnicmp(v5, L"A", 1u) )
      break;
    for ( j = v5 + 2; *j == 32; ++j )
      ;
    if ( *j != 59 )
    {
      SidForString = -1073741811;
      goto LABEL_73;
    }
    do
      ++j;
    while ( *j == 32 );
    if ( *j != 59 )
    {
      do
      {
        while ( *j == 32 )
          ++j;
        if ( (unsigned int)SepSddlLookupAccessMaskInTable(j) )
        {
          v21 |= v29;
          v24 = v30;
          v27 = v21;
        }
        else
        {
          SepSddlParseWideStringUlong(j, &v30, &v27);
          v24 = v30;
          v21 = v27;
          if ( v30 == j )
          {
            SidForString = -1073741811;
            goto LABEL_40;
          }
        }
        j = v24;
      }
      while ( *v24 != 59 );
    }
    ++j;
LABEL_40:
    if ( SidForString )
      goto LABEL_73;
    v23 = 2;
    do
    {
      while ( *j == 32 )
        ++j;
      if ( *j != 59 )
        SidForString = -1073741811;
      ++j;
      --v23;
    }
    while ( v23 );
    if ( SidForString )
      goto LABEL_73;
    while ( *j == 32 )
      ++j;
    SidForString = SepSddlGetSidForString(j);
    if ( SidForString )
      goto LABEL_73;
    v25 = v26;
    if ( !v26 )
      goto LABEL_69;
    if ( *v26 == 32 )
    {
      do
        ++v25;
      while ( *v25 == 32 );
      v26 = v25;
    }
    if ( *v25 != 41 )
    {
LABEL_69:
      SidForString = -1073741705;
      goto LABEL_73;
    }
    v5 = v25 + 1;
    if ( *v5 == 40 )
      ++v5;
    if ( ++v20 >= v16 )
      goto LABEL_72;
  }
  SidForString = -1073741811;
LABEL_72:
  if ( SidForString )
  {
LABEL_73:
    ExFreePoolWithTag(*v3, 0);
    *v3 = nullptr;
  }
  else
  {
    *((_WORD *)*v3 + 1) = v28;
  }
  return SidForString;
}
// 140006DD4: conditional instruction was optimized away because r14d.4!=0
// 140006F63: conditional instruction was optimized away because %var_50.8==0
// 140006C40: variables would overlap: edx.4 and rdx.8

//----- (0000000140006FFC) ----------------------------------------------------
__int64 __fastcall SepSddlDaclFromSDDLString(_WORD *a1, int a2, int *a3, PVOID *a4)
{
  wchar_t *v7; // rcx
  int v8; // edi
  unsigned int AclForString; // ebx
  _WORD *i; // rax
  PVOID P; // [rsp+40h] [rbp+8h] BYREF
  _WORD *v12; // [rsp+50h] [rbp+18h]

  *a4 = nullptr;
  *a3 = 0;
  while ( *a1 == 32 )
    ++a1;
  if ( *a1 != 68 || a1[1] != 58 )
    return 3221225485LL;
  v7 = a1 + 2;
  v8 = a2 != 0 ? 8 : 0;
  if ( *v7 == 80 )
  {
    ++v7;
    v8 |= 0x1000u;
  }
  AclForString = SepSddlGetAclForString(v7, (int)&P);
  if ( AclForString )
    goto LABEL_15;
  for ( i = v12; *i == 32; ++i )
    ;
  if ( *i )
  {
    AclForString = -1073741811;
LABEL_15:
    if ( P )
      ExFreePoolWithTag(P, 0);
    return AclForString;
  }
  *a4 = P;
  *a3 = v8;
  return AclForString;
}

//----- (00000001400070BC) ----------------------------------------------------
__int64 __fastcall SepSddlSecurityDescriptorFromSDDLString(__int64 a1, __int64 a2, _QWORD *a3)
{
  void *v4; // rdi
  NTSTATUS v5; // ebx
  PVOID PoolWithTag; // rax
  PACL Dacl; // [rsp+20h] [rbp-38h] BYREF
  _BYTE SecurityDescriptor[2]; // [rsp+28h] [rbp-30h] BYREF
  __int16 v10; // [rsp+2Ah] [rbp-2Eh]
  ULONG BufferLength; // [rsp+70h] [rbp+18h] BYREF
  __int16 v12; // [rsp+78h] [rbp+20h] BYREF

  Dacl = nullptr;
  v4 = nullptr;
  *a3 = 0;
  v5 = SepSddlDaclFromSDDLString(a1, a2, &v12, &Dacl);
  if ( v5 >= 0 )
  {
    RtlCreateSecurityDescriptor(SecurityDescriptor, 1u);
    RtlSetDaclSecurityDescriptor(SecurityDescriptor, 1u, Dacl, 0);
    BufferLength = 0;
    v10 |= v12;
    RtlAbsoluteToSelfRelativeSD(SecurityDescriptor, nullptr, &BufferLength);
    PoolWithTag = ExAllocatePoolWithTag(PagedPool, BufferLength, 0x64536553u);
    v4 = PoolWithTag;
    if ( PoolWithTag )
    {
      v5 = RtlAbsoluteToSelfRelativeSD(SecurityDescriptor, PoolWithTag, &BufferLength);
      if ( v5 >= 0 )
      {
        ExFreePoolWithTag(Dacl, 0);
        *a3 = v4;
        return (unsigned int)v5;
      }
    }
    else
    {
      v5 = -1073741670;
    }
  }
  if ( Dacl )
    ExFreePoolWithTag(Dacl, 0);
  if ( v4 )
    ExFreePoolWithTag(v4, 0);
  return (unsigned int)v5;
}
// 140006FFC: using guessed type __int64 __fastcall SepSddlDaclFromSDDLString(_QWORD, _QWORD, _QWORD, _QWORD);

//----- (00000001400071B8) ----------------------------------------------------
__int64 __fastcall SeSddlSecurityDescriptorFromSDDL(unsigned __int16 *a1, unsigned int a2, _QWORD *a3)
{
  unsigned __int64 v3; // r9
  __int64 v7; // rcx
  _WORD *PoolWithTag; // rax
  _WORD *v10; // rsi
  unsigned int v11; // ebx

  v3 = *a1;
  if ( a1[1] == v3 + 2 )
  {
    v7 = *((_QWORD *)a1 + 1);
    if ( !*(_WORD *)(v7 + 2 * (v3 >> 1)) )
      return SepSddlSecurityDescriptorFromSDDLString(v7, a2, a3);
  }
  PoolWithTag = ExAllocatePoolWithTag(PagedPool, v3 + 2, 0x73546553u);
  v10 = PoolWithTag;
  if ( PoolWithTag )
  {
    memmove(PoolWithTag, *((const void **)a1 + 1), *a1);
    v10[(unsigned __int64)*a1 >> 1] = 0;
    v11 = SepSddlSecurityDescriptorFromSDDLString((__int64)v10, a2, a3);
    ExFreePoolWithTag(v10, 0);
    return v11;
  }
  else
  {
    *a3 = 0;
    return 3221225626LL;
  }
}

//----- (000000014000727C) ----------------------------------------------------
void __fastcall SeSetSecurityAccessMask(char a1, _DWORD *a2)
{
  *a2 = 0;
  if ( (a1 & 1) != 0 || (a1 & 2) != 0 )
    *a2 = 0x80000;
  if ( (a1 & 4) != 0 )
    *a2 |= 0x40000u;
  if ( (a1 & 8) != 0 )
    *a2 |= 0x1000000u;
}

//----- (00000001400072A4) ----------------------------------------------------
__int64 __fastcall SeUtilSecurityInfoFromSecurityDescriptor(PSECURITY_DESCRIPTOR SecurityDescriptor)
{
  unsigned __int8 *v1; // rdx
  _DWORD *v2; // r8
  _DWORD *v3; // rsi
  unsigned __int8 *v4; // rbp
  __int64 result; // rax
  int v7; // ebx
  PSID Owner; // [rsp+20h] [rbp-28h] BYREF
  PACL Sacl[4]; // [rsp+28h] [rbp-20h] BYREF
  unsigned __int8 OwnerDefaulted; // [rsp+58h] [rbp+10h] BYREF
  unsigned __int8 SaclPresent; // [rsp+68h] [rbp+20h] BYREF

  *v1 = 0;
  v3 = v2;
  v4 = v1;
  *v2 = 0;
  LODWORD(result) = RtlGetOwnerSecurityDescriptor(SecurityDescriptor, &Owner, &OwnerDefaulted);
  if ( (int)result >= 0 )
  {
    v7 = Owner != nullptr;
    LODWORD(result) = RtlGetGroupSecurityDescriptor(SecurityDescriptor, &Owner, &OwnerDefaulted);
    if ( (int)result >= 0 )
    {
      if ( Owner )
        v7 |= 2u;
      LODWORD(result) = RtlGetSaclSecurityDescriptor(SecurityDescriptor, &SaclPresent, Sacl, &OwnerDefaulted);
      if ( (int)result >= 0 )
      {
        if ( SaclPresent )
          v7 |= 8u;
        LODWORD(result) = RtlGetDaclSecurityDescriptor(SecurityDescriptor, &SaclPresent, Sacl, &OwnerDefaulted);
        if ( (int)result >= 0 )
        {
          if ( SaclPresent )
            v7 |= 4u;
          *v4 = OwnerDefaulted;
          *v3 = v7;
          return 0;
        }
      }
    }
  }
  return result;
}
// 1400072B0: variable 'v1' is possibly undefined
// 1400072B5: variable 'v2' is possibly undefined

//----- (000000014000736C) ----------------------------------------------------
__int64 __fastcall CmpRegUtilAllocateUnicodeString(__int64 a1, unsigned __int16 a2)
{
  PVOID PoolWithTag; // rax

  *(_WORD *)a1 = 0;
  *(_WORD *)(a1 + 2) = a2 + 2;
  PoolWithTag = ExAllocatePoolWithTag(PagedPool, a2 + 2LL, 0x63557050u);
  *(_QWORD *)(a1 + 8) = PoolWithTag;
  return PoolWithTag == nullptr ? 0xC000009A : 0;
}

//----- (00000001400073B4) ----------------------------------------------------
__int64 __fastcall CmRegUtilUcValueSetUcString(HANDLE KeyHandle, PUNICODE_STRING ValueName)
{
  unsigned __int16 *v2; // r8
  unsigned __int64 v4; // rdx
  unsigned __int16 *v5; // rdi
  int v7; // ebx
  const void *v8; // rdx
  struct _UNICODE_STRING UnicodeString; // [rsp+30h] [rbp-18h] BYREF

  v4 = *v2;
  v5 = v2;
  if ( v2[1] - (unsigned int)v4 < 2 )
  {
    v7 = CmpRegUtilAllocateUnicodeString((__int64)&UnicodeString, v4);
    if ( v7 >= 0 )
    {
      v8 = *((const void **)v5 + 1);
      UnicodeString.Length = *v5;
      memmove(UnicodeString.Buffer, v8, UnicodeString.Length);
      UnicodeString.Buffer[(unsigned __int64)UnicodeString.Length >> 1] = 0;
      v7 = ZwSetValueKey(KeyHandle, ValueName, 0, 1u, UnicodeString.Buffer, UnicodeString.Length + 2);
      RtlFreeUnicodeString(&UnicodeString);
    }
  }
  else
  {
    *(_WORD *)(*((_QWORD *)v2 + 1) + 2 * (v4 >> 1)) = 0;
    return (unsigned int)ZwSetValueKey(KeyHandle, ValueName, 0, 1u, *((PVOID *)v2 + 1), *v2 + 2);
  }
  return (unsigned int)v7;
}
// 1400073D5: variable 'v2' is possibly undefined

//----- (00000001400074B0) ----------------------------------------------------
NTSTATUS __fastcall CmRegUtilUcValueGetDword(void *a1, struct _UNICODE_STRING *a2, int a3, _DWORD *a4)
{
  NTSTATUS result; // eax
  ULONG v7; // [rsp+30h] [rbp-28h] BYREF
  _DWORD v8[4]; // [rsp+38h] [rbp-20h] BYREF

  result = ZwQueryValueKey(a1, a2, KeyValuePartialInformation, v8, 0x10u, &v7);
  if ( result >= 0 )
  {
    if ( v8[1] == 4 )
      a3 = v8[3];
    else
      result = -1073741788;
  }
  *a4 = a3;
  return result;
}

//----- (0000000140007524) ----------------------------------------------------
__int64 __fastcall CmRegUtilCreateUcKey(
        void *a1,
        struct _UNICODE_STRING *a2,
        ACCESS_MASK a3,
        ULONG a4,
        void *a5,
        _DWORD *a6,
        _QWORD *a7)
{
  NTSTATUS v7; // r11d
  void *v8; // rdx
  int v9; // ecx
  struct _OBJECT_ATTRIBUTES v11; // [rsp+40h] [rbp-38h] BYREF
  void *v12; // [rsp+80h] [rbp+8h] BYREF

  v11.Length = 48;
  v11.RootDirectory = a1;
  v11.Attributes = 576;
  v11.SecurityQualityOfService = nullptr;
  v11.SecurityDescriptor = a5;
  v11.ObjectName = a2;
  v7 = ZwCreateKey(&v12, a3, &v11, 0, nullptr, a4, (PULONG)&a5);
  if ( v7 >= 0 )
  {
    v9 = (int)a5;
    v8 = v12;
  }
  else
  {
    v8 = nullptr;
    v9 = 0;
  }
  *a7 = v8;
  if ( a6 )
    *a6 = v9;
  return (unsigned int)v7;
}

//----- (00000001400075BC) ----------------------------------------------------
NTSTATUS __fastcall CmRegUtilOpenExistingUcKey(void *a1, struct _UNICODE_STRING *a2, ACCESS_MASK a3, _QWORD *a4)
{
  NTSTATUS result; // eax
  struct _OBJECT_ATTRIBUTES v6; // [rsp+20h] [rbp-38h] BYREF
  void *v7; // [rsp+60h] [rbp+8h] BYREF

  *a4 = 0;
  v6.Length = 48;
  v6.RootDirectory = a1;
  v6.Attributes = 576;
  v6.SecurityDescriptor = nullptr;
  v6.SecurityQualityOfService = nullptr;
  v6.ObjectName = a2;
  result = ZwOpenKey(&v7, a3, &v6);
  if ( result >= 0 )
    *a4 = v7;
  return result;
}

//----- (0000000140007614) ----------------------------------------------------
__int64 __fastcall CmRegUtilWstrValueSetWstrString(HANDLE KeyHandle, PCWSTR SourceString, PCWSTR a3)
{
  __int64 result; // rax
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-28h] BYREF
  struct _UNICODE_STRING ValueName; // [rsp+30h] [rbp-18h] BYREF

  LODWORD(result) = WdmlibRtlInitUnicodeStringEx(&DestinationString, a3);
  if ( (int)result >= 0 )
  {
    LODWORD(result) = WdmlibRtlInitUnicodeStringEx(&ValueName, SourceString);
    if ( (int)result >= 0 )
      return CmRegUtilUcValueSetUcString(KeyHandle, &ValueName);
  }
  return result;
}

//----- (0000000140007664) ----------------------------------------------------
__int64 __fastcall CmRegUtilWstrValueSetUcString(HANDLE KeyHandle)
{
  const WCHAR *v1; // rdx
  __int64 result; // rax
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-18h] BYREF

  LODWORD(result) = WdmlibRtlInitUnicodeStringEx(&DestinationString, v1);
  if ( (int)result >= 0 )
    return CmRegUtilUcValueSetUcString(KeyHandle, &DestinationString);
  return result;
}
// 140007679: variable 'v1' is possibly undefined

//----- (00000001400076A0) ----------------------------------------------------
__int64 __usercall CmRegUtilWstrValueSetFullBuffer@<rax>(HANDLE KeyHandle@<rcx>, ULONG DataSize)
{
  const WCHAR *v2; // rdx
  ULONG v3; // r8d
  void *v4; // r9
  void *Data; // rbx
  ULONG v7; // edi
  __int64 result; // rax
  struct _UNICODE_STRING ValueName; // [rsp+30h] [rbp-18h] BYREF

  Data = v4;
  v7 = v3;
  LODWORD(result) = WdmlibRtlInitUnicodeStringEx(&ValueName, v2);
  if ( (int)result >= 0 )
    LODWORD(result) = ZwSetValueKey(KeyHandle, &ValueName, 0, v7, Data, DataSize);
  return result;
}
// 1400076B7: variable 'v4' is possibly undefined
// 1400076BA: variable 'v3' is possibly undefined
// 1400076BD: variable 'v2' is possibly undefined

//----- (00000001400076F8) ----------------------------------------------------
int __fastcall CmRegUtilWstrValueGetDword(void *a1, const WCHAR *a2, int a3, _DWORD *a4)
{
  int result; // eax
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-18h] BYREF

  result = WdmlibRtlInitUnicodeStringEx(&DestinationString, a2);
  if ( result >= 0 )
    return CmRegUtilUcValueGetDword(a1, &DestinationString, a3, a4);
  return result;
}

//----- (0000000140007744) ----------------------------------------------------
NTSTATUS __fastcall CmRegUtilCreateWstrKey(
        void *a1,
        const WCHAR *a2,
        ACCESS_MASK a3,
        ULONG a4,
        void *a5,
        _DWORD *a6,
        _QWORD *a7)
{
  NTSTATUS result; // eax
  struct _UNICODE_STRING DestinationString; // [rsp+40h] [rbp-18h] BYREF

  result = WdmlibRtlInitUnicodeStringEx(&DestinationString, a2);
  if ( result >= 0 )
    return CmRegUtilCreateUcKey(a1, &DestinationString, a3, a4, a5, a6, a7);
  return result;
}

//----- (00000001400077B4) ----------------------------------------------------
int __fastcall CmRegUtilOpenExistingWstrKey(void *a1, const WCHAR *a2, ACCESS_MASK a3, _QWORD *a4)
{
  int result; // eax
  struct _UNICODE_STRING DestinationString; // [rsp+20h] [rbp-18h] BYREF

  result = WdmlibRtlInitUnicodeStringEx(&DestinationString, a2);
  if ( result >= 0 )
    return CmRegUtilOpenExistingUcKey(a1, &DestinationString, a3, a4);
  return result;
}

//----- (0000000140007800) ----------------------------------------------------
__int64 __usercall CmRegUtilUcValueGetFullBuffer@<rax>(
        HANDLE KeyHandle@<rcx>,
        PUNICODE_STRING ValueName@<rdx>,
        __int64 a3)
{
  int v3; // r8d
  int v4; // r9d
  _QWORD *v5; // rbp
  int v6; // esi
  unsigned int v9; // eax
  ULONG Length; // edi
  _DWORD *PoolWithTag; // rbx
  NTSTATUS v13; // edi
  _DWORD *v14; // rax
  ULONG ResultLength; // [rsp+68h] [rbp+20h] BYREF

  v5 = (_QWORD *)a3;
  v6 = v3;
  *(_QWORD *)a3 = 0;
  v9 = (ValueName->Length + 31) & 0xFFFFFFF8;
  Length = v9 + v4;
  if ( v9 + v4 < v9 )
    return 3221225621LL;
  PoolWithTag = ExAllocatePoolWithTag(NonPagedPool, Length, 0x62527050u);
  if ( !PoolWithTag )
    return 3221225626LL;
  v13 = ZwQueryValueKey(KeyHandle, ValueName, KeyValueFullInformation, PoolWithTag, Length, &ResultLength);
  if ( v13 < 0 )
  {
    ExFreePoolWithTag(PoolWithTag, 0);
    if ( v13 != -2147483643 && v13 != -1073741789 )
      return (unsigned int)v13;
    v14 = ExAllocatePoolWithTag(NonPagedPool, ResultLength, 0x62527050u);
    PoolWithTag = v14;
    if ( !v14 )
      return 3221225626LL;
    v13 = ZwQueryValueKey(KeyHandle, ValueName, KeyValueFullInformation, v14, ResultLength, &ResultLength);
    if ( v13 < 0 )
    {
LABEL_13:
      ExFreePoolWithTag(PoolWithTag, 0);
      return (unsigned int)v13;
    }
  }
  if ( v6 && PoolWithTag[1] != v6 )
  {
    v13 = -1073741788;
    goto LABEL_13;
  }
  *v5 = PoolWithTag;
  return 0;
}
// 14000781D: variable 'v3' is possibly undefined
// 140007834: variable 'v4' is possibly undefined

//----- (0000000140007934) ----------------------------------------------------
__int64 __usercall CmRegUtilWstrValueGetFullBuffer@<rax>(HANDLE KeyHandle@<rcx>, __int64 a2)
{
  const WCHAR *v2; // rdx
  __int64 result; // rax
  struct _UNICODE_STRING DestinationString; // [rsp+30h] [rbp-18h] BYREF

  LODWORD(result) = WdmlibRtlInitUnicodeStringEx(&DestinationString, v2);
  if ( (int)result >= 0 )
    return CmRegUtilUcValueGetFullBuffer(KeyHandle, &DestinationString, a2);
  return result;
}
// 140007951: variable 'v2' is possibly undefined

// nfuncs=57 queued=52 decompiled=52 lumina nreq=0 worse=0 better=0
// ALL OK, 52 function(s) have been successfully decompiled
